name: Nix ROS overlay build action
description: Action that builds all packages in the Nix ROS overlay
author: Ben Wolsieffer
inputs:
  nix-file:
    description: Nix file to evaluate
    required: true
    default: release.nix
  root-attribute:
    description: Root attribute to begin evaluation
    required: true
    default: rosPackages
  system:
    description: Host system name (e.g. x86_64-linux). If different from the runner architecture, binfmt/qemu must be configured.
    required: false
  eval-jobs:
    description: Number of evaluations to run in parallel
    required: true
    default: "4"
  build-jobs:
    description: Number of builds to run in parallel
    required: true
    default: "2"
  cachix-cache:
    description: Name of the Cachix cache to use
    required: true
    default: ros

runs:
  using: node20
  main: dist/index.js
