
# Copyright 2019 Open Source Robotics Foundation
# Distributed under the terms of the BSD license

{ lib, buildRosPackage, fetchurl, rtt-roscomm, catkin, geometry-msgs, rtt-std-msgs }:
buildRosPackage {
  pname = "ros-kinetic-rtt-geometry-msgs";
  version = "2.9.1";

  src = fetchurl {
    url = https://github.com/orocos-gbp/rtt_ros_integration-release/archive/release/kinetic/rtt_geometry_msgs/2.9.1-0.tar.gz;
    sha256 = "b0616d896086de891b683784413868d4700f5ed18cff2a56f82c93c15bb173c6";
  };

  buildInputs = [ rtt-roscomm rtt-std-msgs geometry-msgs ];
  propagatedBuildInputs = [ rtt-roscomm rtt-std-msgs geometry-msgs ];
  nativeBuildInputs = [ catkin ];

  meta = {
    description = ''Provides an rtt typekit for ROS geometry_msgs messages.

    It allows you to use ROS messages transparently in
    RTT components and applications.

    This package was automatically generated by the
    create_rtt_msgs generator and should not be manually
    modified.

    See the http://ros.org/wiki/geometry_msgs documentation
    for the documentation of the ROS messages in this
    typekit.'';
    license = with lib.licenses; [ bsdOriginal ];
  };
}
