
# Copyright 2019 Open Source Robotics Foundation
# Distributed under the terms of the BSD license

{ lib, buildRosPackage, fetchurl, rtt-roscomm, catkin, actionlib-msgs, rtt-std-msgs }:
buildRosPackage {
  pname = "ros-kinetic-rtt-actionlib-msgs";
  version = "2.9.1";

  src = fetchurl {
    url = https://github.com/orocos-gbp/rtt_ros_integration-release/archive/release/kinetic/rtt_actionlib_msgs/2.9.1-0.tar.gz;
    sha256 = "0a5c9eeca6677a6d77f762133a83ab145a4c972dffa2742d92174ec70229a350";
  };

  buildInputs = [ rtt-roscomm rtt-std-msgs actionlib-msgs ];
  propagatedBuildInputs = [ rtt-roscomm rtt-std-msgs actionlib-msgs ];
  nativeBuildInputs = [ catkin ];

  meta = {
    description = ''Provides an rtt typekit for ROS actionlib_msgs messages.

    It allows you to use ROS messages transparently in
    RTT components and applications.

    This package was automatically generated by the
    create_rtt_msgs generator and should not be manually
    modified.

    See the http://ros.org/wiki/actionlib_msgs documentation
    for the documentation of the ROS messages in this
    typekit.'';
    #license = lib.licenses.BSD;
  };
}
