
# Copyright 2019 Open Source Robotics Foundation
# Distributed under the terms of the BSD license

{ lib, buildRosPackage, fetchurl, rtt-std-msgs, rtt-geometry-msgs, sensor-msgs, catkin, rtt-roscomm }:
buildRosPackage {
  pname = "ros-kinetic-rtt-sensor-msgs";
  version = "2.9.1";

  src = fetchurl {
    url = https://github.com/orocos-gbp/rtt_ros_integration-release/archive/release/kinetic/rtt_sensor_msgs/2.9.1-0.tar.gz;
    sha256 = "5d6cd8214dc084d78619073a76e6cefa91cd78294fb95e6cabb2aea5e97a43d5";
  };

  buildInputs = [ rtt-roscomm rtt-geometry-msgs sensor-msgs rtt-std-msgs ];
  propagatedBuildInputs = [ rtt-roscomm rtt-geometry-msgs sensor-msgs rtt-std-msgs ];
  nativeBuildInputs = [ catkin ];

  meta = {
    description = ''Provides an rtt typekit for ROS sensor_msgs messages.

    It allows you to use ROS messages transparently in
    RTT components and applications.

    This package was automatically generated by the
    create_rtt_msgs generator and should not be manually
    modified.

    See the http://ros.org/wiki/sensor_msgs documentation
    for the documentation of the ROS messages in this
    typekit.'';
    license = with lib.licenses; [ bsdOriginal ];
  };
}
