
# Copyright 2019 Open Source Robotics Foundation
# Distributed under the terms of the BSD license

{ lib, buildRosPackage, fetchurl, rtt-std-msgs, rtt-geometry-msgs, rtt-sensor-msgs, catkin, rtt-roscomm, stereo-msgs }:
buildRosPackage {
  pname = "ros-lunar-rtt-stereo-msgs";
  version = "2.9.2-r1";

  src = fetchurl {
    url = https://github.com/orocos-gbp/rtt_ros_integration-release/archive/release/lunar/rtt_stereo_msgs/2.9.2-1.tar.gz;
    sha256 = "2f9757f38bf43ff07eaee28245d4217325b0d1ae67684ebd4ab27544f6aac176";
  };

  buildInputs = [ rtt-std-msgs rtt-geometry-msgs rtt-sensor-msgs rtt-roscomm stereo-msgs ];
  propagatedBuildInputs = [ rtt-std-msgs rtt-geometry-msgs rtt-sensor-msgs rtt-roscomm stereo-msgs ];
  nativeBuildInputs = [ catkin ];

  meta = {
    description = ''Provides an rtt typekit for ROS stereo_msgs messages.

    It allows you to use ROS messages transparently in
    RTT components and applications.

    This package was automatically generated by the
    create_rtt_msgs generator and should not be manually
    modified.

    See the http://ros.org/wiki/stereo_msgs documentation
    for the documentation of the ROS messages in this
    typekit.'';
    license = with lib.licenses; [ bsdOriginal ];
  };
}
