
# Copyright 2019 Open Source Robotics Foundation
# Distributed under the terms of the BSD license

{ lib, buildRosPackage, fetchurl, shape-msgs, rtt-std-msgs, rtt-geometry-msgs, catkin, rtt-roscomm }:
buildRosPackage {
  pname = "ros-kinetic-rtt-shape-msgs";
  version = "2.9.1";

  src = fetchurl {
    url = https://github.com/orocos-gbp/rtt_ros_integration-release/archive/release/kinetic/rtt_shape_msgs/2.9.1-0.tar.gz;
    sha256 = "012869bfea0aa3c1f693337048fccc8c1d6bc5eddc3e1583f56eb438d443ef1d";
  };

  buildInputs = [ rtt-roscomm shape-msgs rtt-std-msgs rtt-geometry-msgs ];
  propagatedBuildInputs = [ rtt-roscomm shape-msgs rtt-std-msgs rtt-geometry-msgs ];
  nativeBuildInputs = [ catkin ];

  meta = {
    description = ''Provides an rtt typekit for ROS shape_msgs messages.

    It allows you to use ROS messages transparently in
    RTT components and applications.

    This package was automatically generated by the
    create_rtt_msgs generator and should not be manually
    modified.

    See the http://ros.org/wiki/shape_msgs documentation
    for the documentation of the ROS messages in this
    typekit.'';
    license = with lib.licenses; [ bsdOriginal ];
  };
}
