
# Copyright 2019 Open Source Robotics Foundation
# Distributed under the terms of the BSD license

{ lib, buildRosPackage, fetchurl, shape-msgs, rtt-std-msgs, rtt-geometry-msgs, catkin, rtt-roscomm }:
buildRosPackage {
  pname = "ros-lunar-rtt-shape-msgs";
  version = "2.9.2-r1";

  src = fetchurl {
    url = https://github.com/orocos-gbp/rtt_ros_integration-release/archive/release/lunar/rtt_shape_msgs/2.9.2-1.tar.gz;
    sha256 = "0952960f0dd8c1df22aab8a946a9d6dd0dd74759e01da50717a939dfe0ed44e4";
  };

  buildInputs = [ rtt-roscomm shape-msgs rtt-std-msgs rtt-geometry-msgs ];
  propagatedBuildInputs = [ rtt-roscomm shape-msgs rtt-std-msgs rtt-geometry-msgs ];
  nativeBuildInputs = [ catkin ];

  meta = {
    description = ''Provides an rtt typekit for ROS shape_msgs messages.

    It allows you to use ROS messages transparently in
    RTT components and applications.

    This package was automatically generated by the
    create_rtt_msgs generator and should not be manually
    modified.

    See the http://ros.org/wiki/shape_msgs documentation
    for the documentation of the ROS messages in this
    typekit.'';
    license = with lib.licenses; [ bsdOriginal ];
  };
}
