
# Copyright 2023 Open Source Robotics Foundation
# Distributed under the terms of the BSD license

{ lib, buildRosPackage, fetchurl, catkin, hector-geotiff, hector-nav-msgs }:
buildRosPackage {
  pname = "ros-noetic-hector-geotiff-plugins";
  version = "0.5.2-r4";

  src = let
      fetchFromGithub = (builtins.import (builtins.fetchTarball ({ url = "https://github.com/NixOS/nixpkgs/archive/aa0e8072a57e879073cee969a780e586dbe57997.tar.gz"; })) ({})).fetchFromGitHub;
    in
      fetchFromGithub {
        owner = "tu-darmstadt-ros-pkg-gbp";
        repo = "hector_slam-release";
        rev = "release/noetic/hector_geotiff_plugins/0.5.2-4";
        sha256 = "sha256-XF1QBO/1yLGNIcYlNJtDP2x5U93r70va2tnd012wpHc=";
      };

  buildType = "catkin";
  buildInputs = [ catkin ];
  propagatedBuildInputs = [ hector-geotiff hector-nav-msgs ];
  nativeBuildInputs = [ catkin ];

  meta = {
    description = ''hector_geotiff_plugins contains plugins that extend geotiff maps generated by hector_geotiff.'';
    license = with lib.licenses; [ bsdOriginal ];
  };
}
