
# Copyright 2021 Open Source Robotics Foundation
# Distributed under the terms of the BSD license

{ lib, buildRosPackage, fetchurl, catkin, hector-geotiff, hector-nav-msgs }:
buildRosPackage {
  pname = "ros-noetic-hector-geotiff-plugins";
  version = "0.5.1-r1";

  src = fetchurl {
    url = "https://github.com/tu-darmstadt-ros-pkg-gbp/hector_slam-release/archive/release/noetic/hector_geotiff_plugins/0.5.1-1.tar.gz";
    name = "0.5.1-1.tar.gz";
    sha256 = "459611623a7d99d6d089fbc3709186cc824a47a3e057dc3d0f3bd6bcd9e2025d";
  };

  buildType = "catkin";
  propagatedBuildInputs = [ hector-geotiff hector-nav-msgs ];
  nativeBuildInputs = [ catkin ];

  meta = {
    description = ''hector_geotiff_plugins contains plugins that extend geotiff maps generated by hector_geotiff.'';
    license = with lib.licenses; [ bsdOriginal ];
  };
}
