
# Copyright 2019 Open Source Robotics Foundation
# Distributed under the terms of the BSD license

{ lib, buildRosPackage, fetchurl, rtt-std-msgs, rtt-geometry-msgs, rtt-sensor-msgs, catkin, rtt-roscomm, stereo-msgs }:
buildRosPackage {
  pname = "ros-kinetic-rtt-stereo-msgs";
  version = "2.9.1";

  src = fetchurl {
    url = https://github.com/orocos-gbp/rtt_ros_integration-release/archive/release/kinetic/rtt_stereo_msgs/2.9.1-0.tar.gz;
    sha256 = "2bab5e9478669f2df3529e0c6bb5c17b98731861e99ff4891e5f1bb1fc488a78";
  };

  propagatedBuildInputs = [ rtt-geometry-msgs rtt-std-msgs rtt-roscomm rtt-sensor-msgs stereo-msgs ];
  nativeBuildInputs = [ rtt-geometry-msgs rtt-std-msgs rtt-roscomm catkin rtt-sensor-msgs stereo-msgs ];

  meta = {
    description = ''Provides an rtt typekit for ROS stereo_msgs messages.

    It allows you to use ROS messages transparently in
    RTT components and applications.

    This package was automatically generated by the
    create_rtt_msgs generator and should not be manually
    modified.

    See the http://ros.org/wiki/stereo_msgs documentation
    for the documentation of the ROS messages in this
    typekit.'';
    #license = lib.licenses.BSD;
  };
}
