
# Copyright 2019 Open Source Robotics Foundation
# Distributed under the terms of the BSD license

{ lib, buildRosPackage, fetchurl, std-msgs, catkin, rtt-ros, rtt-roscomm }:
buildRosPackage {
  pname = "ros-kinetic-rtt-std-msgs";
  version = "2.9.1";

  src = fetchurl {
    url = https://github.com/orocos-gbp/rtt_ros_integration-release/archive/release/kinetic/rtt_std_msgs/2.9.1-0.tar.gz;
    sha256 = "153103599d56264a493bb8b986baf15fee2274806851d8f3605132b39572ae61";
  };

  buildInputs = [ std-msgs rtt-ros rtt-roscomm ];
  propagatedBuildInputs = [ std-msgs rtt-ros rtt-roscomm ];
  nativeBuildInputs = [ catkin ];

  meta = {
    description = ''Provides an rtt typekit for ROS std_msgs messages.

    It allows you to use ROS messages transparently in
    RTT components and applications.

    This package was automatically generated by the
    create_rtt_msgs generator and should not be manually
    modified.

    See the http://ros.org/wiki/std_msgs documentation
    for the documentation of the ROS messages in this
    typekit.'';
    license = with lib.licenses; [ bsdOriginal ];
  };
}
