
# Copyright 2021 Open Source Robotics Foundation
# Distributed under the terms of the BSD license

{ lib, buildRosPackage, fetchurl, catkin, xpp-examples, xpp-hyq, xpp-msgs, xpp-quadrotor, xpp-states, xpp-vis }:
buildRosPackage {
  pname = "ros-kinetic-xpp";
  version = "1.0.10";

  src = fetchurl {
    url = "https://github.com/leggedrobotics/xpp-release/archive/release/kinetic/xpp/1.0.10-0.tar.gz";
    name = "1.0.10-0.tar.gz";
    sha256 = "0feaa34c3484037c786a467734b32694e6c6a5cf6a54431fd0332d89fdf138a6";
  };

  buildType = "catkin";
  propagatedBuildInputs = [ xpp-examples xpp-hyq xpp-msgs xpp-quadrotor xpp-states xpp-vis ];
  nativeBuildInputs = [ catkin ];

  meta = {
    description = ''Visualization of motion-plans for legged robots. It draws support areas, 
    contact forces and motion trajectories in RVIZ and displays URDFs for 
    specific robots, including a one-legged, a two-legged hopper and
    <a href="http://dls.iit.it/">HyQ</a>. 
    Example motions were generated by
    <a href="https://github.com/ethz-adrl/towr">towr</a>.'';
    license = with lib.licenses; [ bsdOriginal ];
  };
}
