
# Copyright 2019 Open Source Robotics Foundation
# Distributed under the terms of the BSD license

{ lib, buildRosPackage, fetchurl, rtt-roscomm, catkin, actionlib-msgs, rtt-std-msgs }:
buildRosPackage {
  pname = "ros-lunar-rtt-actionlib-msgs";
  version = "2.9.2-r1";

  src = fetchurl {
    url = https://github.com/orocos-gbp/rtt_ros_integration-release/archive/release/lunar/rtt_actionlib_msgs/2.9.2-1.tar.gz;
    sha256 = "3dc22351d6587257287bcb9e34cc8656c0268a3d793e09d8cb992551c2d7b014";
  };

  buildInputs = [ rtt-roscomm rtt-std-msgs actionlib-msgs ];
  propagatedBuildInputs = [ rtt-roscomm rtt-std-msgs actionlib-msgs ];
  nativeBuildInputs = [ catkin ];

  meta = {
    description = ''Provides an rtt typekit for ROS actionlib_msgs messages.

    It allows you to use ROS messages transparently in
    RTT components and applications.

    This package was automatically generated by the
    create_rtt_msgs generator and should not be manually
    modified.

    See the http://ros.org/wiki/actionlib_msgs documentation
    for the documentation of the ROS messages in this
    typekit.'';
    license = with lib.licenses; [ bsdOriginal ];
  };
}
