
# Copyright 2021 Open Source Robotics Foundation
# Distributed under the terms of the BSD license

{ lib, buildRosPackage, fetchurl, catkin, genmsg, rtt-roscomm, std-srvs }:
buildRosPackage {
  pname = "ros-kinetic-rtt-std-srvs";
  version = "2.9.2-r1";

  src = fetchurl {
    url = "https://github.com/orocos-gbp/rtt_ros_integration-release/archive/release/kinetic/rtt_std_srvs/2.9.2-1.tar.gz";
    name = "2.9.2-1.tar.gz";
    sha256 = "bf969875f8bddc1196100c3c24e23c078be0a1b3ccb6c533c9586a469475fc9b";
  };

  buildType = "catkin";
  propagatedBuildInputs = [ genmsg rtt-roscomm std-srvs ];
  nativeBuildInputs = [ catkin ];

  meta = {
    description = ''Provides an rtt typekit for ROS std_msgs messages.

    It allows you to use ROS messages transparently in
    RTT components and applications.

    This package was automatically generated by the
    create_rtt_msgs generator and should not be manually
    modified.

    See the http://ros.org/wiki/std_msgs documentation
    for the documentation of the ROS messages in this
    typekit.'';
    license = with lib.licenses; [ bsdOriginal ];
  };
}
