name: Update colcon packages
on:
  schedule:
    - cron: "0 12 * * FRI"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: ros
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - name: Configure git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Update colcon
        run: maintainers/scripts/update-colcon.sh --build --commit
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: colcon-updates
          delete-branch: true
          title: 'Colcon updates'
          body: |
            Automated changes by `maintainers/scripts/update-colcon.sh`
