
# Copyright 2019 Open Source Robotics Foundation
# Distributed under the terms of the BSD license

{ lib, buildRosPackage, fetchurl, rtt-roscomm, rosgraph-msgs, catkin, rtt-std-msgs }:
buildRosPackage {
  pname = "ros-kinetic-rtt-rosgraph-msgs";
  version = "2.9.1";

  src = fetchurl {
    url = https://github.com/orocos-gbp/rtt_ros_integration-release/archive/release/kinetic/rtt_rosgraph_msgs/2.9.1-0.tar.gz;
    sha256 = "5b3d9d4447f9b64818d07b55e31a37dc8104d8cfda4242822de88a76a4676c50";
  };

  propagatedBuildInputs = [ rtt-roscomm rosgraph-msgs rtt-std-msgs ];
  nativeBuildInputs = [ rtt-roscomm rosgraph-msgs catkin rtt-std-msgs ];

  meta = {
    description = ''Provides an rtt typekit for ROS rosgraph_msgs messages.

    It allows you to use ROS messages transparently in
	RTT components and applications.

	This package was automatically generated by the
	create_rtt_msgs generator and should not be manually
	modified.

	See the http://ros.org/wiki/rosgraph_msgs documentation
	for the documentation of the ROS messages in this
	typekit.'';
    #license = lib.licenses.BSD;
  };
}
